import 'package:flutter/material.dart';

import 'models.dart';

const wordCategories = <WordCategory>[
  WordCategory(
    id: 'animals',
    name: 'Animals',
    words: [
      'LION',
      'TIGER',
      'PANDA',
      'WOLF',
      'KOALA',
      'MONKEY',
      'ZEBRA',
      'HIPPO',
      'PARROT',
      'EAGLE',
      'PENGUIN',
      'DOLPHIN',
      'GIRAFFE',
      'ELEPHANT',
      'CHEETAH',
      'PYTHON',
      'GORILLA',
      'LEOPARD',
      'JAGUAR',
      'RHINO',
      'FLAMINGO',
      'KANGAROO',
      'SHARK',
      'PEACOCK',
      'FALCON',
    ],
    description: 'Safari & Wildlife',
    accentColor: Color(0xFFF97316),
    gradientStart: Color(0xFFF97316),
    gradientEnd: Color(0xFFFBBF24),
    assetPath: 'assets/categories/animals.webp',
  ),
  WordCategory(
    id: 'food',
    name: 'Food',
    words: [
      'PIZZA',
      'BURGER',
      'MANGO',
      'PASTA',
      'TACOS',
      'WAFFLE',
      'SUSHI',
      'RAMEN',
      'STEAK',
      'SALMON',
      'BROWNIE',
      'CURRY',
      'PRETZEL',
      'DUMPLING',
      'CROISSANT',
      'LASAGNA',
      'BURRITO',
      'RISOTTO',
      'TEMPURA',
      'PAELLA',
      'TIRAMISU',
      'FALAFEL',
      'GNOCCHI',
      'FONDUE',
      'SASHIMI',
    ],
    description: 'World Cuisine',
    accentColor: Color(0xFFF472B6),
    gradientStart: Color(0xFFEF4444),
    gradientEnd: Color(0xFFF97316),
    assetPath: 'assets/categories/food.webp',
  ),
  WordCategory(
    id: 'nature',
    name: 'Nature',
    words: [
      'RIVER',
      'OCEAN',
      'CLOUD',
      'FOREST',
      'DUNE',
      'RAINBOW',
      'THUNDER',
      'CANYON',
      'MEADOW',
      'RAPIDS',
      'VOLCANO',
      'GLACIER',
      'MOUNTAIN',
      'SAVANNA',
      'WATERFALL',
      'TUNDRA',
      'DELTA',
      'WETLAND',
      'PRAIRIE',
      'PLATEAU',
      'LAGOON',
      'GEYSER',
      'FJORD',
      'ESTUARY',
      'MANGROVE',
    ],
    description: "Earth's Wonders",
    accentColor: Color(0xFF4ADE80),
    gradientStart: Color(0xFF16A34A),
    gradientEnd: Color(0xFF0891B2),
    assetPath: 'assets/categories/nature.webp',
  ),
  WordCategory(
    id: 'sports',
    name: 'Sports',
    words: [
      'SOCCER',
      'TENNIS',
      'GOLF',
      'JUDO',
      'SKIING',
      'BOXING',
      'HOCKEY',
      'CYCLING',
      'DIVING',
      'KARATE',
      'SURFING',
      'RUGBY',
      'ARCHERY',
      'BASEBALL',
      'SWIMMING',
      'FENCING',
      'CRICKET',
      'MARATHON',
      'VOLLEYBALL',
      'BADMINTON',
      'HANDBALL',
      'ROWING',
      'WRESTLING',
      'POLO',
      'SQUASH',
    ],
    description: 'Athletic Challenges',
    accentColor: Color(0xFF10B981),
    gradientStart: Color(0xFF0891B2),
    gradientEnd: Color(0xFF10B981),
    assetPath: 'assets/categories/sports.webp',
  ),
  WordCategory(
    id: 'space',
    name: 'Space',
    words: [
      'MOON',
      'MARS',
      'COMET',
      'VENUS',
      'PLANET',
      'ROCKET',
      'SATURN',
      'METEOR',
      'ORBIT',
      'ECLIPSE',
      'AURORA',
      'JUPITER',
      'NEPTUNE',
      'TELESCOPE',
      'ASTRONAUT',
      'GALAXY',
      'NEBULA',
      'COSMOS',
      'PULSAR',
      'QUASAR',
      'ASTEROID',
      'URANUS',
      'SATELLITE',
      'GRAVITY',
      'SUPERNOVA',
    ],
    description: 'Cosmic Exploration',
    accentColor: Color(0xFF818CF8),
    gradientStart: Color(0xFF4338CA),
    gradientEnd: Color(0xFF7C3AED),
    assetPath: 'assets/categories/space.webp',
  ),
  WordCategory(
    id: 'tech',
    name: 'STEM',
    words: [
      'PIXEL',
      'BINARY',
      'ROUTER',
      'BROWSER',
      'SERVER',
      'NETWORK',
      'CACHE',
      'TERMINAL',
      'FUNCTION',
      'VARIABLE',
      'DATABASE',
      'SYNTAX',
      'ALGORITHM',
      'COMPILER',
      'CLOUD',
      'KERNEL',
      'POINTER',
      'PROTOCOL',
      'FIREWALL',
      'BACKEND',
      'FRONTEND',
      'DEPLOY',
      'PIPELINE',
      'CLUSTER',
      'RUNTIME',
    ],
    description: 'Coding & Science',
    accentColor: Color(0xFF38BDF8),
    gradientStart: Color(0xFF2563EB),
    gradientEnd: Color(0xFF0891B2),
    assetPath: 'assets/categories/tech.webp',
  ),
];
