class WordLearningEntry {
  const WordLearningEntry({
    required this.word,
    required this.en,
    required this.zh,
    required this.ko,
  });

  final String word;
  final String en;
  final String zh;
  final String ko;

  String meaningFor(String languageCode) {
    return switch (languageCode) {
      'zh' => zh,
      'ko' => ko,
      _ => en,
    };
  }
}

WordLearningEntry wordLearningEntryFor(String word) {
  final normalized = word.toUpperCase();
  return _wordLearningEntries[normalized] ??
      WordLearningEntry(
        word: normalized,
        en: 'A useful English word',
        zh: '一个有用的英文单词',
        ko: '유용한 영어 단어',
      );
}

const _wordLearningEntries = <String, WordLearningEntry>{
  'LION': WordLearningEntry(
    word: 'LION',
    en: 'large wild cat',
    zh: '狮子',
    ko: '사자',
  ),
  'TIGER': WordLearningEntry(
    word: 'TIGER',
    en: 'striped wild cat',
    zh: '老虎',
    ko: '호랑이',
  ),
  'ELEPHANT': WordLearningEntry(
    word: 'ELEPHANT',
    en: 'huge animal with a trunk',
    zh: '大象',
    ko: '코끼리',
  ),
  'GIRAFFE': WordLearningEntry(
    word: 'GIRAFFE',
    en: 'tall animal with a long neck',
    zh: '长颈鹿',
    ko: '기린',
  ),
  'ZEBRA': WordLearningEntry(
    word: 'ZEBRA',
    en: 'striped horse-like animal',
    zh: '斑马',
    ko: '얼룩말',
  ),
  'MONKEY': WordLearningEntry(
    word: 'MONKEY',
    en: 'playful tree animal',
    zh: '猴子',
    ko: '원숭이',
  ),
  'PENGUIN': WordLearningEntry(
    word: 'PENGUIN',
    en: 'flightless sea bird',
    zh: '企鹅',
    ko: '펭귄',
  ),
  'DOLPHIN': WordLearningEntry(
    word: 'DOLPHIN',
    en: 'smart sea mammal',
    zh: '海豚',
    ko: '돌고래',
  ),
  'EAGLE': WordLearningEntry(
    word: 'EAGLE',
    en: 'large hunting bird',
    zh: '鹰',
    ko: '독수리',
  ),
  'PYTHON': WordLearningEntry(
    word: 'PYTHON',
    en: 'large snake',
    zh: '蟒蛇',
    ko: '비단뱀',
  ),
  'CHEETAH': WordLearningEntry(
    word: 'CHEETAH',
    en: 'very fast wild cat',
    zh: '猎豹',
    ko: '치타',
  ),
  'GORILLA': WordLearningEntry(
    word: 'GORILLA',
    en: 'large ape',
    zh: '大猩猩',
    ko: '고릴라',
  ),
  'LEOPARD': WordLearningEntry(
    word: 'LEOPARD',
    en: 'spotted wild cat',
    zh: '豹',
    ko: '표범',
  ),
  'JAGUAR': WordLearningEntry(
    word: 'JAGUAR',
    en: 'powerful spotted cat',
    zh: '美洲豹',
    ko: '재규어',
  ),
  'RHINO': WordLearningEntry(
    word: 'RHINO',
    en: 'horned heavy animal',
    zh: '犀牛',
    ko: '코뿔소',
  ),
  'HIPPO': WordLearningEntry(
    word: 'HIPPO',
    en: 'large river animal',
    zh: '河马',
    ko: '하마',
  ),
  'FLAMINGO': WordLearningEntry(
    word: 'FLAMINGO',
    en: 'pink long-legged bird',
    zh: '火烈鸟',
    ko: '플라밍고',
  ),
  'PARROT': WordLearningEntry(
    word: 'PARROT',
    en: 'colorful talking bird',
    zh: '鹦鹉',
    ko: '앵무새',
  ),
  'KOALA': WordLearningEntry(
    word: 'KOALA',
    en: 'tree-dwelling marsupial',
    zh: '考拉',
    ko: '코알라',
  ),
  'PANDA': WordLearningEntry(
    word: 'PANDA',
    en: 'black and white bear',
    zh: '熊猫',
    ko: '판다',
  ),
  'KANGAROO': WordLearningEntry(
    word: 'KANGAROO',
    en: 'jumping animal with a pouch',
    zh: '袋鼠',
    ko: '캥거루',
  ),
  'WOLF': WordLearningEntry(
    word: 'WOLF',
    en: 'wild dog-like animal',
    zh: '狼',
    ko: '늑대',
  ),
  'SHARK': WordLearningEntry(
    word: 'SHARK',
    en: 'large ocean predator',
    zh: '鲨鱼',
    ko: '상어',
  ),
  'PEACOCK': WordLearningEntry(
    word: 'PEACOCK',
    en: 'bird with bright tail feathers',
    zh: '孔雀',
    ko: '공작',
  ),
  'FALCON': WordLearningEntry(
    word: 'FALCON',
    en: 'fast hunting bird',
    zh: '猎鹰',
    ko: '매',
  ),
  'GALAXY': WordLearningEntry(
    word: 'GALAXY',
    en: 'huge group of stars',
    zh: '星系',
    ko: '은하',
  ),
  'NEBULA': WordLearningEntry(
    word: 'NEBULA',
    en: 'cloud of gas in space',
    zh: '星云',
    ko: '성운',
  ),
  'COMET': WordLearningEntry(
    word: 'COMET',
    en: 'icy object with a tail',
    zh: '彗星',
    ko: '혜성',
  ),
  'PLANET': WordLearningEntry(
    word: 'PLANET',
    en: 'world orbiting a star',
    zh: '行星',
    ko: '행성',
  ),
  'SATURN': WordLearningEntry(
    word: 'SATURN',
    en: 'ringed planet',
    zh: '土星',
    ko: '토성',
  ),
  'METEOR': WordLearningEntry(
    word: 'METEOR',
    en: 'space rock streaking in sky',
    zh: '流星',
    ko: '유성',
  ),
  'COSMOS': WordLearningEntry(
    word: 'COSMOS',
    en: 'the universe',
    zh: '宇宙',
    ko: '우주',
  ),
  'ORBIT': WordLearningEntry(
    word: 'ORBIT',
    en: 'path around a planet or star',
    zh: '轨道',
    ko: '궤도',
  ),
  'PULSAR': WordLearningEntry(
    word: 'PULSAR',
    en: 'spinning star that pulses',
    zh: '脉冲星',
    ko: '펄서',
  ),
  'QUASAR': WordLearningEntry(
    word: 'QUASAR',
    en: 'very bright distant object',
    zh: '类星体',
    ko: '퀘이사',
  ),
  'ECLIPSE': WordLearningEntry(
    word: 'ECLIPSE',
    en: 'when one body blocks light',
    zh: '日食/月食',
    ko: '식',
  ),
  'ASTEROID': WordLearningEntry(
    word: 'ASTEROID',
    en: 'small rocky space object',
    zh: '小行星',
    ko: '소행성',
  ),
  'JUPITER': WordLearningEntry(
    word: 'JUPITER',
    en: 'largest planet',
    zh: '木星',
    ko: '목성',
  ),
  'NEPTUNE': WordLearningEntry(
    word: 'NEPTUNE',
    en: 'blue outer planet',
    zh: '海王星',
    ko: '해왕성',
  ),
  'URANUS': WordLearningEntry(
    word: 'URANUS',
    en: 'tilted ice giant planet',
    zh: '天王星',
    ko: '천왕성',
  ),
  'VENUS': WordLearningEntry(
    word: 'VENUS',
    en: 'bright hot planet',
    zh: '金星',
    ko: '금성',
  ),
  'MARS': WordLearningEntry(
    word: 'MARS',
    en: 'the red planet',
    zh: '火星',
    ko: '화성',
  ),
  'MOON': WordLearningEntry(
    word: 'MOON',
    en: 'natural satellite',
    zh: '月亮',
    ko: '달',
  ),
  'TELESCOPE': WordLearningEntry(
    word: 'TELESCOPE',
    en: 'tool for seeing far away',
    zh: '望远镜',
    ko: '망원경',
  ),
  'ASTRONAUT': WordLearningEntry(
    word: 'ASTRONAUT',
    en: 'person who travels in space',
    zh: '宇航员',
    ko: '우주비행사',
  ),
  'SATELLITE': WordLearningEntry(
    word: 'SATELLITE',
    en: 'object orbiting a planet',
    zh: '卫星',
    ko: '위성',
  ),
  'GRAVITY': WordLearningEntry(
    word: 'GRAVITY',
    en: 'force that pulls things down',
    zh: '重力',
    ko: '중력',
  ),
  'ROCKET': WordLearningEntry(
    word: 'ROCKET',
    en: 'vehicle launched into space',
    zh: '火箭',
    ko: '로켓',
  ),
  'AURORA': WordLearningEntry(
    word: 'AURORA',
    en: 'colorful polar lights',
    zh: '极光',
    ko: '오로라',
  ),
  'SUPERNOVA': WordLearningEntry(
    word: 'SUPERNOVA',
    en: 'exploding star',
    zh: '超新星',
    ko: '초신성',
  ),
  'SOCCER': WordLearningEntry(
    word: 'SOCCER',
    en: 'football game',
    zh: '足球',
    ko: '축구',
  ),
  'TENNIS': WordLearningEntry(
    word: 'TENNIS',
    en: 'racket sport',
    zh: '网球',
    ko: '테니스',
  ),
  'HOCKEY': WordLearningEntry(
    word: 'HOCKEY',
    en: 'stick and puck sport',
    zh: '曲棍球/冰球',
    ko: '하키',
  ),
  'BASEBALL': WordLearningEntry(
    word: 'BASEBALL',
    en: 'bat and ball sport',
    zh: '棒球',
    ko: '야구',
  ),
  'SWIMMING': WordLearningEntry(
    word: 'SWIMMING',
    en: 'moving through water',
    zh: '游泳',
    ko: '수영',
  ),
  'CYCLING': WordLearningEntry(
    word: 'CYCLING',
    en: 'riding a bicycle',
    zh: '骑行',
    ko: '사이클',
  ),
  'BOXING': WordLearningEntry(
    word: 'BOXING',
    en: 'fighting with gloves',
    zh: '拳击',
    ko: '복싱',
  ),
  'SKIING': WordLearningEntry(
    word: 'SKIING',
    en: 'sliding on snow',
    zh: '滑雪',
    ko: '스키',
  ),
  'ARCHERY': WordLearningEntry(
    word: 'ARCHERY',
    en: 'shooting arrows',
    zh: '射箭',
    ko: '양궁',
  ),
  'FENCING': WordLearningEntry(
    word: 'FENCING',
    en: 'sword sport',
    zh: '击剑',
    ko: '펜싱',
  ),
  'DIVING': WordLearningEntry(
    word: 'DIVING',
    en: 'jumping or swimming underwater',
    zh: '跳水/潜水',
    ko: '다이빙',
  ),
  'JUDO': WordLearningEntry(
    word: 'JUDO',
    en: 'martial art',
    zh: '柔道',
    ko: '유도',
  ),
  'GOLF': WordLearningEntry(
    word: 'GOLF',
    en: 'club and ball sport',
    zh: '高尔夫',
    ko: '골프',
  ),
  'RUGBY': WordLearningEntry(
    word: 'RUGBY',
    en: 'team ball sport',
    zh: '橄榄球',
    ko: '럭비',
  ),
  'CRICKET': WordLearningEntry(
    word: 'CRICKET',
    en: 'bat and ball game',
    zh: '板球',
    ko: '크리켓',
  ),
  'KARATE': WordLearningEntry(
    word: 'KARATE',
    en: 'martial art',
    zh: '空手道',
    ko: '가라테',
  ),
  'SURFING': WordLearningEntry(
    word: 'SURFING',
    en: 'riding ocean waves',
    zh: '冲浪',
    ko: '서핑',
  ),
  'MARATHON': WordLearningEntry(
    word: 'MARATHON',
    en: 'long running race',
    zh: '马拉松',
    ko: '마라톤',
  ),
  'VOLLEYBALL': WordLearningEntry(
    word: 'VOLLEYBALL',
    en: 'net ball sport',
    zh: '排球',
    ko: '배구',
  ),
  'BADMINTON': WordLearningEntry(
    word: 'BADMINTON',
    en: 'shuttlecock sport',
    zh: '羽毛球',
    ko: '배드민턴',
  ),
  'HANDBALL': WordLearningEntry(
    word: 'HANDBALL',
    en: 'team sport played by hand',
    zh: '手球',
    ko: '핸드볼',
  ),
  'ROWING': WordLearningEntry(
    word: 'ROWING',
    en: 'moving a boat with oars',
    zh: '赛艇',
    ko: '조정',
  ),
  'WRESTLING': WordLearningEntry(
    word: 'WRESTLING',
    en: 'grappling sport',
    zh: '摔跤',
    ko: '레슬링',
  ),
  'POLO': WordLearningEntry(
    word: 'POLO',
    en: 'horse and mallet sport',
    zh: '马球',
    ko: '폴로',
  ),
  'SQUASH': WordLearningEntry(
    word: 'SQUASH',
    en: 'indoor racket sport',
    zh: '壁球',
    ko: '스쿼시',
  ),
  'PIZZA': WordLearningEntry(
    word: 'PIZZA',
    en: 'baked flatbread with toppings',
    zh: '披萨',
    ko: '피자',
  ),
  'BURGER': WordLearningEntry(
    word: 'BURGER',
    en: 'sandwich with a patty',
    zh: '汉堡',
    ko: '버거',
  ),
  'SUSHI': WordLearningEntry(
    word: 'SUSHI',
    en: 'Japanese rice dish',
    zh: '寿司',
    ko: '초밥',
  ),
  'PASTA': WordLearningEntry(
    word: 'PASTA',
    en: 'Italian noodle dish',
    zh: '意面',
    ko: '파스타',
  ),
  'TACOS': WordLearningEntry(
    word: 'TACOS',
    en: 'folded tortilla food',
    zh: '塔可',
    ko: '타코',
  ),
  'RAMEN': WordLearningEntry(
    word: 'RAMEN',
    en: 'noodle soup',
    zh: '拉面',
    ko: '라멘',
  ),
  'CURRY': WordLearningEntry(
    word: 'CURRY',
    en: 'spiced sauce dish',
    zh: '咖喱',
    ko: '카레',
  ),
  'STEAK': WordLearningEntry(
    word: 'STEAK',
    en: 'thick slice of meat',
    zh: '牛排',
    ko: '스테이크',
  ),
  'SALMON': WordLearningEntry(
    word: 'SALMON',
    en: 'pink fish',
    zh: '三文鱼',
    ko: '연어',
  ),
  'MANGO': WordLearningEntry(
    word: 'MANGO',
    en: 'sweet tropical fruit',
    zh: '芒果',
    ko: '망고',
  ),
  'WAFFLE': WordLearningEntry(
    word: 'WAFFLE',
    en: 'grid-pattern cake',
    zh: '华夫饼',
    ko: '와플',
  ),
  'DUMPLING': WordLearningEntry(
    word: 'DUMPLING',
    en: 'filled dough food',
    zh: '饺子',
    ko: '만두',
  ),
  'LASAGNA': WordLearningEntry(
    word: 'LASAGNA',
    en: 'layered pasta dish',
    zh: '千层面',
    ko: '라자냐',
  ),
  'BURRITO': WordLearningEntry(
    word: 'BURRITO',
    en: 'wrapped tortilla meal',
    zh: '墨西哥卷饼',
    ko: '부리토',
  ),
  'RISOTTO': WordLearningEntry(
    word: 'RISOTTO',
    en: 'creamy rice dish',
    zh: '意式烩饭',
    ko: '리소토',
  ),
  'TEMPURA': WordLearningEntry(
    word: 'TEMPURA',
    en: 'lightly fried food',
    zh: '天妇罗',
    ko: '튀김',
  ),
  'PAELLA': WordLearningEntry(
    word: 'PAELLA',
    en: 'Spanish rice dish',
    zh: '西班牙海鲜饭',
    ko: '파에야',
  ),
  'CROISSANT': WordLearningEntry(
    word: 'CROISSANT',
    en: 'buttery crescent pastry',
    zh: '可颂',
    ko: '크루아상',
  ),
  'TIRAMISU': WordLearningEntry(
    word: 'TIRAMISU',
    en: 'coffee dessert',
    zh: '提拉米苏',
    ko: '티라미수',
  ),
  'BROWNIE': WordLearningEntry(
    word: 'BROWNIE',
    en: 'chocolate dessert square',
    zh: '布朗尼',
    ko: '브라우니',
  ),
  'PRETZEL': WordLearningEntry(
    word: 'PRETZEL',
    en: 'twisted baked snack',
    zh: '椒盐卷饼',
    ko: '프레첼',
  ),
  'FALAFEL': WordLearningEntry(
    word: 'FALAFEL',
    en: 'fried chickpea ball',
    zh: '炸鹰嘴豆丸',
    ko: '팔라펠',
  ),
  'GNOCCHI': WordLearningEntry(
    word: 'GNOCCHI',
    en: 'small potato dumplings',
    zh: '意式面疙瘩',
    ko: '뇨키',
  ),
  'FONDUE': WordLearningEntry(
    word: 'FONDUE',
    en: 'melted cheese dip',
    zh: '奶酪火锅',
    ko: '퐁뒤',
  ),
  'SASHIMI': WordLearningEntry(
    word: 'SASHIMI',
    en: 'sliced raw fish',
    zh: '刺身',
    ko: '사시미',
  ),
  'ALGORITHM': WordLearningEntry(
    word: 'ALGORITHM',
    en: 'step-by-step method',
    zh: '算法',
    ko: '알고리즘',
  ),
  'DATABASE': WordLearningEntry(
    word: 'DATABASE',
    en: 'organized data storage',
    zh: '数据库',
    ko: '데이터베이스',
  ),
  'NETWORK': WordLearningEntry(
    word: 'NETWORK',
    en: 'connected computers or people',
    zh: '网络',
    ko: '네트워크',
  ),
  'SERVER': WordLearningEntry(
    word: 'SERVER',
    en: 'computer that provides services',
    zh: '服务器',
    ko: '서버',
  ),
  'PIXEL': WordLearningEntry(
    word: 'PIXEL',
    en: 'tiny dot on a screen',
    zh: '像素',
    ko: '픽셀',
  ),
  'BINARY': WordLearningEntry(
    word: 'BINARY',
    en: 'using two values',
    zh: '二进制',
    ko: '이진',
  ),
  'CLOUD': WordLearningEntry(
    word: 'CLOUD',
    en: 'online computing storage',
    zh: '云',
    ko: '클라우드',
  ),
  'ROUTER': WordLearningEntry(
    word: 'ROUTER',
    en: 'device that directs network traffic',
    zh: '路由器',
    ko: '라우터',
  ),
  'KERNEL': WordLearningEntry(
    word: 'KERNEL',
    en: 'core of an operating system',
    zh: '内核',
    ko: '커널',
  ),
  'SYNTAX': WordLearningEntry(
    word: 'SYNTAX',
    en: 'rules of code or language',
    zh: '语法',
    ko: '문법',
  ),
  'CACHE': WordLearningEntry(
    word: 'CACHE',
    en: 'fast temporary storage',
    zh: '缓存',
    ko: '캐시',
  ),
  'POINTER': WordLearningEntry(
    word: 'POINTER',
    en: 'reference to a memory location',
    zh: '指针',
    ko: '포인터',
  ),
  'FUNCTION': WordLearningEntry(
    word: 'FUNCTION',
    en: 'reusable block of code',
    zh: '函数',
    ko: '함수',
  ),
  'VARIABLE': WordLearningEntry(
    word: 'VARIABLE',
    en: 'named value in code',
    zh: '变量',
    ko: '변수',
  ),
  'COMPILER': WordLearningEntry(
    word: 'COMPILER',
    en: 'tool that translates code',
    zh: '编译器',
    ko: '컴파일러',
  ),
  'BROWSER': WordLearningEntry(
    word: 'BROWSER',
    en: 'app for viewing websites',
    zh: '浏览器',
    ko: '브라우저',
  ),
  'PROTOCOL': WordLearningEntry(
    word: 'PROTOCOL',
    en: 'rules for communication',
    zh: '协议',
    ko: '프로토콜',
  ),
  'FIREWALL': WordLearningEntry(
    word: 'FIREWALL',
    en: 'network security barrier',
    zh: '防火墙',
    ko: '방화벽',
  ),
  'TERMINAL': WordLearningEntry(
    word: 'TERMINAL',
    en: 'command-line interface',
    zh: '终端',
    ko: '터미널',
  ),
  'BACKEND': WordLearningEntry(
    word: 'BACKEND',
    en: 'server-side part of an app',
    zh: '后端',
    ko: '백엔드',
  ),
  'FRONTEND': WordLearningEntry(
    word: 'FRONTEND',
    en: 'user-facing part of an app',
    zh: '前端',
    ko: '프론트엔드',
  ),
  'DEPLOY': WordLearningEntry(
    word: 'DEPLOY',
    en: 'publish software for use',
    zh: '部署',
    ko: '배포',
  ),
  'PIPELINE': WordLearningEntry(
    word: 'PIPELINE',
    en: 'automated workflow',
    zh: '流水线',
    ko: '파이프라인',
  ),
  'CLUSTER': WordLearningEntry(
    word: 'CLUSTER',
    en: 'group of connected systems',
    zh: '集群',
    ko: '클러스터',
  ),
  'RUNTIME': WordLearningEntry(
    word: 'RUNTIME',
    en: 'environment where code runs',
    zh: '运行时',
    ko: '런타임',
  ),
  'FOREST': WordLearningEntry(
    word: 'FOREST',
    en: 'large area of trees',
    zh: '森林',
    ko: '숲',
  ),
  'RIVER': WordLearningEntry(
    word: 'RIVER',
    en: 'flowing body of water',
    zh: '河流',
    ko: '강',
  ),
  'MOUNTAIN': WordLearningEntry(
    word: 'MOUNTAIN',
    en: 'very high landform',
    zh: '山',
    ko: '산',
  ),
  'OCEAN': WordLearningEntry(
    word: 'OCEAN',
    en: 'vast body of salt water',
    zh: '海洋',
    ko: '바다',
  ),
  'THUNDER': WordLearningEntry(
    word: 'THUNDER',
    en: 'sound after lightning',
    zh: '雷声',
    ko: '천둥',
  ),
  'RAINBOW': WordLearningEntry(
    word: 'RAINBOW',
    en: 'colored arc after rain',
    zh: '彩虹',
    ko: '무지개',
  ),
  'GLACIER': WordLearningEntry(
    word: 'GLACIER',
    en: 'slow-moving ice mass',
    zh: '冰川',
    ko: '빙하',
  ),
  'VOLCANO': WordLearningEntry(
    word: 'VOLCANO',
    en: 'mountain that erupts lava',
    zh: '火山',
    ko: '화산',
  ),
  'CANYON': WordLearningEntry(
    word: 'CANYON',
    en: 'deep valley with steep sides',
    zh: '峡谷',
    ko: '협곡',
  ),
  'SAVANNA': WordLearningEntry(
    word: 'SAVANNA',
    en: 'grassy tropical plain',
    zh: '稀树草原',
    ko: '사바나',
  ),
  'TUNDRA': WordLearningEntry(
    word: 'TUNDRA',
    en: 'cold treeless plain',
    zh: '苔原',
    ko: '툰드라',
  ),
  'DELTA': WordLearningEntry(
    word: 'DELTA',
    en: 'river mouth landform',
    zh: '三角洲',
    ko: '삼각주',
  ),
  'WATERFALL': WordLearningEntry(
    word: 'WATERFALL',
    en: 'falling stream of water',
    zh: '瀑布',
    ko: '폭포',
  ),
  'WETLAND': WordLearningEntry(
    word: 'WETLAND',
    en: 'marshy water-rich land',
    zh: '湿地',
    ko: '습지',
  ),
  'PRAIRIE': WordLearningEntry(
    word: 'PRAIRIE',
    en: 'wide grassy plain',
    zh: '草原',
    ko: '대초원',
  ),
  'PLATEAU': WordLearningEntry(
    word: 'PLATEAU',
    en: 'high flat land',
    zh: '高原',
    ko: '고원',
  ),
  'LAGOON': WordLearningEntry(
    word: 'LAGOON',
    en: 'shallow coastal water',
    zh: '潟湖',
    ko: '석호',
  ),
  'GEYSER': WordLearningEntry(
    word: 'GEYSER',
    en: 'hot spring that erupts',
    zh: '间歇泉',
    ko: '간헐천',
  ),
  'FJORD': WordLearningEntry(
    word: 'FJORD',
    en: 'narrow sea inlet by cliffs',
    zh: '峡湾',
    ko: '피오르',
  ),
  'ESTUARY': WordLearningEntry(
    word: 'ESTUARY',
    en: 'where river meets sea',
    zh: '河口',
    ko: '하구',
  ),
  'MANGROVE': WordLearningEntry(
    word: 'MANGROVE',
    en: 'coastal tree habitat',
    zh: '红树林',
    ko: '맹그로브',
  ),
  'MEADOW': WordLearningEntry(
    word: 'MEADOW',
    en: 'field of grass and flowers',
    zh: '草地',
    ko: '초원',
  ),
  'CAVERN': WordLearningEntry(
    word: 'CAVERN',
    en: 'large cave',
    zh: '洞穴',
    ko: '동굴',
  ),
  'DUNE': WordLearningEntry(
    word: 'DUNE',
    en: 'hill of sand',
    zh: '沙丘',
    ko: '모래언덕',
  ),
  'RAPIDS': WordLearningEntry(
    word: 'RAPIDS',
    en: 'fast rough river water',
    zh: '急流',
    ko: '급류',
  ),
};
